// packages/react-app/src/products/ProductList.tsx
import React, { useEffect } from "react";
import { makeStyles } from "@material-ui/core/styles";
import { CircularProgress, Grid, Container, Box, Typography } from "@material-ui/core";
import ProductItem from "./ProductItem";
import { dependenciesLocator } from "@frontend-clean-architecture/core";
import { usePlocState } from "../common/usePlocState";

const ploc = dependenciesLocator.provideProductsPloc();
const useStyles = makeStyles(theme => ({
    titleContainer: { marginBottom: theme.spacing(4) },
    cardGrid: { paddingTop: theme.spacing(4), paddingBottom: theme.spacing(4) },
    infoContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
    },
}));
const ProductList: React.FC = () => {
    const classes = useStyles();
    const state = usePlocState(ploc);
    React.useEffect(() => {
        const searchProducts = async (filter: string) => {
            ploc.search(filter);
        };
        searchProducts("Element");
    }, [ploc]);

    switch (state.kind) {
        case "LoadingProductsState": {
            return (
                <div className={classes.infoContainer}>
                    {" "}
                    <CircularProgress />{" "}
                </div>
            );
        }
        case "ErrorProductsState": {
            return (
                <div className={classes.infoContainer}>
                    {" "}
                    <Typography display="inline" variant="h5" component="h2">
                        {" "}
                        {state.error}{" "}
                    </Typography>{" "}
                </div>
            );
        }
        case "LoadedProductsState": {
            return (
                <Container className={classes.cardGrid} maxWidth="xl">
                    {" "}
                    <Box className={classes.titleContainer}>
                        {" "}
                        <Typography display="inline" variant="h6" component="h2">
                            {" "}
                            {"Results for "}{" "}
                        </Typography>{" "}
                        <Typography color="primary" display="inline" variant="h6" component="h2">
                            {" "}
                            {"Element"}{" "}
                        </Typography>{" "}
                    </Box>{" "}
                    <Grid container spacing={2}>
                        {" "}
                        {state.products.map((product, index) => (
                            <ProductItem product={product} key={index} />
                        ))}{" "}
                    </Grid>{" "}
                </Container>
            );
        }
    }
};
export default ProductList;

// packages/vue-app/src/products/ProductList.vue
<template>
    <div id="info-container" v-if="state.kind === 'LoadingProductsState'">
        <ProgressSpinner />
    </div>
    <div id="info-container" v-if="state.kind === 'ErrorProductsState'">Error</div>
    <div id="products-container" idv-if="state.kind === 'LoadedProductsState'">
        <h2>Results for "{{ state.searchTerm }}"</h2>

        <div class="p-grid">
            <div
                class="p-col-6 p-md-4 p-lg-3 p-xl-2"
                v-for="product in state.products"
                v-bind:key="product.id"
            >
                <ProductItem v-bind="product" />
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import { dependenciesLocator } from "@frontend-clean-architecture/core";
import { usePlocState } from "../common/usePlocState";
import ProductItem from "./ProductItem.vue";

export default defineComponent({
    components: {
        ProductItem,
    },
    props: {
        searchTerm: {
            type: String,
            required: true,
        },
    },
    setup(props) {
        const ploc = dependenciesLocator.provideProductsPloc();
        const state = usePlocState(ploc);

        onMounted(() => {
            ploc.search(props.searchTerm);
        });

        return { state };
    },
});
</script>

<style scoped>
#products-container {
    padding: 16px;
}
#info-container {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
}
</style>
